# Generated by Django 5.2.6 on 2026-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier used by the template layer.",
                        max_length=60,
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "short_description",
                    models.TextField(help_text="Used on cards and listings."),
                ),
                ("full_description", models.TextField(blank=True)),
                (
                    "deliverables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of deliverables, e.g. ["Keyword research", "On-page fixes"].',
                    ),
                ),
                (
                    "starting_price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Starting price in KES. Leave blank if quoted case-by-case.",
                        null=True,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=180)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
