# Generated by Django 5.2.6 on 2026-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("essential", "Essential Growth"),
                            ("standard", "Standard Growth"),
                            ("premium", "Premium Growth"),
                            ("website", "Website Development"),
                            ("other", "Something else"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_15k", "Under KES 15,000"),
                            ("15k_25k", "KES 15,000–25,000"),
                            ("25k_45k", "KES 25,000–45,000"),
                            ("45k_plus", "KES 45,000+"),
                            ("unsure", "Not sure yet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the admin notification email was delivered successfully.",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
