# Generated by Django 5.2.6 on 2026-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly retainer"),
                            ("one_time", "One-time service"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(help_text="Current price in KES."),
                ),
                (
                    "reference_price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Original/reference price in KES, shown struck through. Optional.",
                        null=True,
                    ),
                ),
                (
                    "price_is_from",
                    models.BooleanField(
                        default=False,
                        help_text="Show the price as a starting point, e.g. 'from KES 30,000'.",
                    ),
                ),
                ("short_description", models.TextField(blank=True)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of included features, in display order.",
                    ),
                ),
                ("ideal_for", models.CharField(blank=True, max_length=240)),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Visually emphasise this package (e.g. the Premium tier).",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "price"],
            },
        ),
    ]
