# Generated by Django 5.2.6 on 2026-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_label",
                    models.CharField(
                        help_text="How the client is described publicly. Use a real, approved label.",
                        max_length=160,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("industry", models.CharField(blank=True, max_length=120)),
                ("challenge", models.TextField()),
                ("solution", models.TextField()),
                ("result", models.TextField()),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Only include metrics VEE can verify.",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="case-studies/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Case studies",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where the subscription came from, e.g. 'home', 'blog-post'.",
                        max_length=80,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tagline",
                    models.CharField(
                        default="Let's grow your brand online together.", max_length=200
                    ),
                ),
                (
                    "phone_calls",
                    models.CharField(
                        default="0717115737",
                        help_text="Public number for voice calls (click-to-call).",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="254759643882",
                        help_text="International format without '+'. Used to build wa.me links.",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="hello@veeagency.co.ke", max_length=254),
                ),
                (
                    "location_label",
                    models.CharField(
                        default="Syokimau, Machakos County, Kenya", max_length=120
                    ),
                ),
                (
                    "service_counties",
                    models.JSONField(
                        default=list,
                        help_text='Counties with stronger local emphasis, e.g. ["Nairobi", "Machakos"].',
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank until the real profile URL is available; the icon stays hidden.",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank until the real profile URL is available; the icon stays hidden.",
                    ),
                ),
                (
                    "default_social_image",
                    models.ImageField(
                        blank=True,
                        help_text="Fallback Open Graph image used when a page has none.",
                        upload_to="site/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_name", models.CharField(max_length=120)),
                ("business", models.CharField(blank=True, max_length=160)),
                ("quote", models.TextField()),
                ("logo", models.ImageField(blank=True, upload_to="testimonials/")),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
