# Generated by Django 5.2.6 on 2026-09-16 10:17

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="service_counties",
            field=models.JSONField(
                blank=True,
                default=apps.core.models.default_service_counties,
                help_text="Counties with stronger local emphasis. Coverage is nationwide regardless.",
            ),
        ),
    ]
