# Generated by Django 5.2.6 on 2026-09-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_sitesettings_service_counties"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ga4_measurement_id",
            field=models.CharField(
                blank=True,
                help_text="Google Analytics 4 ID, e.g. G-XXXXXXXXXX. Only loads after cookie consent.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_site_verification",
            field=models.CharField(
                blank=True,
                help_text="Google Search Console verification token (the content value only, not the whole meta tag). Sets no cookie, so it needs no consent.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_pixel_id",
            field=models.CharField(
                blank=True,
                help_text="Meta (Facebook) Pixel ID. Only loads after cookie consent.",
                max_length=40,
            ),
        ),
    ]
