# Generated by Django 5.2.6 on 2026-09-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_ga4_measurement_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="signup_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Recorded to rate-limit automated signups. Not used for anything else.",
                null=True,
            ),
        ),
    ]
