# Generated by Django 5.2.6 on 2026-09-16 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=240, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short summary used on listings and cards."
                    ),
                ),
                (
                    "quick_answer",
                    models.TextField(
                        blank=True,
                        help_text="Direct answer shown in the Quick Answer box, for AEO/featured snippets.",
                    ),
                ),
                ("body", models.TextField()),
                ("featured_image", models.ImageField(blank=True, upload_to="blog/")),
                ("featured_image_alt", models.CharField(blank=True, max_length=200)),
                (
                    "faqs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of {"question": ..., "answer": ...} used for FAQ schema.',
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=180)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.category"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
