# Generated by Django 5.2.6 on 2026-09-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=models.TextField(
                help_text="Markdown. Use ## for subheadings, - for bullets, **bold**, and [text](/services/) to link to other pages on the site."
            ),
        ),
    ]
