# Generated by Django 5.2.6 on 2026-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("county", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("hero_headline", models.CharField(max_length=200)),
                ("intro", models.TextField()),
                ("body", models.TextField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=180)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "featured_services",
                    models.ManyToManyField(
                        blank=True, related_name="location_pages", to="services.service"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "county"],
            },
        ),
    ]
